# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScannerPlus' do
  use_frameworks!
  pod 'LiquidFloatingActionButton', :git => 'https://github.com/alexsanderkhitev/LiquidFloatingActionButton.git'

end
